import logging

from app.services.rag_service import RAGService

logger = logging.getLogger(__name__)

# Initialize only once
rag_service = RAGService()


def chat(message: str):
    """
    Main chat service.

    Parameters
    ----------
    message : str
        User's legal query.

    Returns
    -------
    dict
        Response generated by the RAG pipeline.
    """

    try:

        if not message or not message.strip():

            return {
                "answer": "Please enter a legal question.",
                "documents": [],
                "sources": [],
                "language": "en",
                "original_query": "",
            }

        logger.info("Received query: %s", message)

        response = rag_service.ask(message.strip())

        logger.info("Response generated successfully.")

        return response

    except Exception as exc:

        logger.exception("Chat Service Error: %s", exc)

        return {
            "answer": (
                "Something went wrong while processing your request. "
                "Please try again."
            ),
            "documents": [],
            "sources": [],
            "language": "en",
            "original_query": message,
        }